# Site settings
title: Caixas GiftBox
subtitle: Rony de Freitas
email: caixasgiftbox@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "http://threefingers.github.io" # the subpath of your site, e.g. /blog
url: "https://threefingers.gitlab.io" # the base hostname & protocol for your site
author: Rony de Freitas
street_address: Rua Codó, 75
city: Conjunto Palmeiras - Fortaleza
state: CE
zip_code:
country: Brasil
phone: (85) 8888-8888

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
  style: compressed
